version: '3'

services:
  # api:
  #   container_name: api
  #   depends_on:
  #     - postgres
  #     - minio
  #   ports:
  #     - 5000:5000
  #   build: .
  #   volumes:
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file: .env
    
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: getfit
      POSTGRES_USER: getfit
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/

  minio:
      container_name: minio
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - minio_storage:/data
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: password
      command: server --console-address ":9001" /data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio password;
      /usr/bin/mc mb myminio/getfitimg;
      /usr/bin/mc mb myminio/profile;
      /usr/bin/mc anonymous set public myminio/getfitimg;
      /usr/bin/mc anonymous set public myminio/profile;
      exit 0;
      "

volumes:
  minio_storage:
  pg_data:
