name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/getfitbe
            git pull
            npm install
            sudo docker compose down -v
            sudo docker rmi $(sudo docker images -q getfitbe-api)
            sudo docker compose up -d